# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x43onfig.proto\x12\rConfiguration\"\'\n\x0fProtocolrequest\x12\x14\n\x0cProtocolname\x18\x01 \x01(\t\"/\n\x0eProtocolConfig\x12\x0c\n\x04Port\x18\x01 \x01(\x05\x12\x0f\n\x07\x61\x64resse\x18\x02 \x01(\t\"1\n\x10\x43onfigParameters\x12\x0c\n\x04Port\x18\x01 \x01(\x05\x12\x0f\n\x07\x61\x64resse\x18\x02 \x01(\t\"#\n\x0fProtocolSetting\x12\x10\n\x08response\x18\x01 \x01(\t2\xa9\x01\n\rConfigManager\x12J\n\tgetConfig\x12\x1e.Configuration.Protocolrequest\x1a\x1d.Configuration.ProtocolConfig\x12L\n\tsetConfig\x12\x1f.Configuration.ConfigParameters\x1a\x1e.Configuration.ProtocolSettingb\x06proto3')



_PROTOCOLREQUEST = DESCRIPTOR.message_types_by_name['Protocolrequest']
_PROTOCOLCONFIG = DESCRIPTOR.message_types_by_name['ProtocolConfig']
_CONFIGPARAMETERS = DESCRIPTOR.message_types_by_name['ConfigParameters']
_PROTOCOLSETTING = DESCRIPTOR.message_types_by_name['ProtocolSetting']
Protocolrequest = _reflection.GeneratedProtocolMessageType('Protocolrequest', (_message.Message,), {
  'DESCRIPTOR' : _PROTOCOLREQUEST,
  '__module__' : 'Config_pb2'
  # @@protoc_insertion_point(class_scope:Configuration.Protocolrequest)
  })
_sym_db.RegisterMessage(Protocolrequest)

ProtocolConfig = _reflection.GeneratedProtocolMessageType('ProtocolConfig', (_message.Message,), {
  'DESCRIPTOR' : _PROTOCOLCONFIG,
  '__module__' : 'Config_pb2'
  # @@protoc_insertion_point(class_scope:Configuration.ProtocolConfig)
  })
_sym_db.RegisterMessage(ProtocolConfig)

ConfigParameters = _reflection.GeneratedProtocolMessageType('ConfigParameters', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGPARAMETERS,
  '__module__' : 'Config_pb2'
  # @@protoc_insertion_point(class_scope:Configuration.ConfigParameters)
  })
_sym_db.RegisterMessage(ConfigParameters)

ProtocolSetting = _reflection.GeneratedProtocolMessageType('ProtocolSetting', (_message.Message,), {
  'DESCRIPTOR' : _PROTOCOLSETTING,
  '__module__' : 'Config_pb2'
  # @@protoc_insertion_point(class_scope:Configuration.ProtocolSetting)
  })
_sym_db.RegisterMessage(ProtocolSetting)

_CONFIGMANAGER = DESCRIPTOR.services_by_name['ConfigManager']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROTOCOLREQUEST._serialized_start=31
  _PROTOCOLREQUEST._serialized_end=70
  _PROTOCOLCONFIG._serialized_start=72
  _PROTOCOLCONFIG._serialized_end=119
  _CONFIGPARAMETERS._serialized_start=121
  _CONFIGPARAMETERS._serialized_end=170
  _PROTOCOLSETTING._serialized_start=172
  _PROTOCOLSETTING._serialized_end=207
  _CONFIGMANAGER._serialized_start=210
  _CONFIGMANAGER._serialized_end=379
# @@protoc_insertion_point(module_scope)
