# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MQTT.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nMQTT.proto\x12\x0cMQTTFunction\"9\n\nComingData\x12\r\n\x05Topic\x18\x01 \x01(\t\x12\x0f\n\x07Payload\x18\x02 \x01(\t\x12\x0b\n\x03Qos\x18\x03 \x01(\x05\"$\n\nACKPublish\x12\x16\n\x0e\x41\x63knowledgment\x18\x01 \x01(\t2V\n\x0bMQTTManager\x12G\n\x0fPublishMessages\x12\x18.MQTTFunction.ComingData\x1a\x18.MQTTFunction.ACKPublish\"\x00\x62\x06proto3')



_COMINGDATA = DESCRIPTOR.message_types_by_name['ComingData']
_ACKPUBLISH = DESCRIPTOR.message_types_by_name['ACKPublish']
ComingData = _reflection.GeneratedProtocolMessageType('ComingData', (_message.Message,), {
  'DESCRIPTOR' : _COMINGDATA,
  '__module__' : 'MQTT_pb2'
  # @@protoc_insertion_point(class_scope:MQTTFunction.ComingData)
  })
_sym_db.RegisterMessage(ComingData)

ACKPublish = _reflection.GeneratedProtocolMessageType('ACKPublish', (_message.Message,), {
  'DESCRIPTOR' : _ACKPUBLISH,
  '__module__' : 'MQTT_pb2'
  # @@protoc_insertion_point(class_scope:MQTTFunction.ACKPublish)
  })
_sym_db.RegisterMessage(ACKPublish)

_MQTTMANAGER = DESCRIPTOR.services_by_name['MQTTManager']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMINGDATA._serialized_start=28
  _COMINGDATA._serialized_end=85
  _ACKPUBLISH._serialized_start=87
  _ACKPUBLISH._serialized_end=123
  _MQTTMANAGER._serialized_start=125
  _MQTTMANAGER._serialized_end=211
# @@protoc_insertion_point(module_scope)
