# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from lib import mqtt_pb2 as mqtt__pb2


class MQTTManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishMessages = channel.unary_unary(
                '/MQTTFunction.MQTTManager/PublishMessages',
                request_serializer=mqtt__pb2.ComingData.SerializeToString,
                response_deserializer=mqtt__pb2.ReturnType.FromString,
                )


class MQTTManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PublishMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MQTTManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishMessages,
                    request_deserializer=mqtt__pb2.ComingData.FromString,
                    response_serializer=mqtt__pb2.ReturnType.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MQTTFunction.MQTTManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MQTTManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PublishMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MQTTFunction.MQTTManager/PublishMessages',
            mqtt__pb2.ComingData.SerializeToString,
            mqtt__pb2.ReturnType.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
